[project]
name = "python-arch-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anton Kaplan", email = "anton.kaplan@live.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "autocommand>=2.2.2",
    "bs4>=0.0.2",
    "lxml>=6.0.2",
    "platformdirs>=4.11.0",
    "requests>=2.32.5",
    "rich>=14.2.0",
]

[project.scripts]
wiki = "python_arch_wiki:__main__.main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
